# Generated by Django 4.2 on 2025-03-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trang_thai',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
