# Generated by Django 4.2 on 2025-03-17 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
